### ISSUE TITLE
[Feature Request] - Additional Fields

### ISSUE THREAD

**Issue by htafolla** [masknetgoal634/near-prometheus-exporter#2]
Thanks for the great work, it has saved me many hours!! A couple of fields are missing to fully complete the challenge. I am hoping they are easy for you to add.

1. Network Version (version->build): 
http post https://rpc.betanet.near.org jsonrpc=2.0 method=status params:='[]' id=dontcare

2. Local Node Version (version->build): 
http post http://localhost:3030 jsonrpc=2.0 method=status params:='[]' id=dontcare

3. Epoch Start Height (epoch_start_height): 
http post https://rpc.testnet.near.org jsonrpc=2.0 method=validators params:='[null]' id=dontcare

**Comment by masknetgoal634** [comment]
I'm not sure how to pass a string values of the local/network version to Prometheus but i converted them to a float values, may be it will helpful. [new_metrics](https://github.com/masknetgoal634/near-prometheus-exporter/commit/93b4ccf880f07fae2cad61743b7df9657d603881) added:
- near_epoch_start_height
- near_version_number
- near_dev_version_number
- near_version_build
- near_dev_version_build

For instance we can to alert when our version not matched with a version of a public node  

```
- alert: NearVersionBuildNotMatched
    expr: near_version_number != near_dev_version_number
    for: 5m
    labels:
      severity: warning
   ....
```
